library(RODBC)
massocpf <- odbcConnectAccess("C:/Data/CampaignFinanceData/Data/campaign-finance-reports.mdb")
tbls <- sqlTables(massocpf)
assetsdisposed <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_ASSETS_DISPOSED")
master <- sqlFetch(massocpf, "vUPLOAD_MASTER")
bankcredits <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_BANK_CREDITS")
cpf9detail <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_CPF9_DETAIL")
cpf9summaries <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_CPF9_SUMMARIES")
expenditures <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_EXPENDITURES")
inkinds <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_INKINDS")
liabilities <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_LIABILITIES")
r1detail <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_R1_DETAIL")
r1summaries <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_R1_SUMMARIES")
receipts <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_RECEIPTS")
subvendoritems <- sqlFetch(massocpf, "vUPLOAD_tCURRENT_SUBVENDOR_ITEMS")
write.csv(assetsdisposed, "assetsdisposed.csv")
write.csv(bankcredits, "bankcredits.csv")
write.csv(cpf9detail, "cpf9detail.csv")
write.csv(cpf9summaries, "cpf9summaries.csv")
write.csv(expenditures, "expenditures.csv")
write.csv(inkinds, "inkinds.csv")
write.csv(liabilities, "liabilities.csv")
write.csv(master, "master.csv")
write.csv(r1detail, "r1detail.csv")
write.csv(r1summaries, "r1summaries.csv")
write.csv(receipts, "receipts.csv")
write.csv(subvendoritems, "subvendoritems.csv")